# Generated by Django 5.2.17 on 2026-08-28 15:42

import books.validators
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('isbn', models.CharField(help_text='ISBN-10 or ISBN-13. Separators are accepted and stripped before storage.', max_length=13, unique=True, validators=[books.validators.validate_isbn])),
                ('cost_usd', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='cost_usd must be greater than 0.')])),
                ('selling_price_local', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('supplier_country', models.CharField(help_text='ISO 3166-1 alpha-2 country code, e.g. ES.', max_length=2, validators=[django.core.validators.RegexValidator(message='supplier_country must be an ISO 3166-1 alpha-2 code.', regex='^[A-Za-z]{2}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('cost_usd__gt', 0)), name='book_cost_usd_positive'), models.CheckConstraint(condition=models.Q(('stock_quantity__gte', 0)), name='book_stock_non_negative')],
            },
        ),
    ]
