# Generated by Django 5.2.17 on 2026-08-28 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_book_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='supplier_country',
            field=models.CharField(help_text='Two-letter country code, e.g. ES.', max_length=2, validators=[django.core.validators.RegexValidator(message='supplier_country must be a two-letter country code.', regex='^[A-Za-z]{2}$')]),
        ),
    ]
