# Generated by Django 6.0.3 on 2026-04-01 03:46

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_cost_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=32, unique=True, validators=[books.models.validate_isbn_digits]),
        ),
    ]
