# Generated by Django 5.2.17 on 2026-08-28 16:46

import books.validators
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_supplier_country_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cost_usd',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='cost_usd debe ser mayor que 0.')]),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='ISBN-10 o ISBN-13. Se aceptan guiones y espacios; se guardan solo los digitos.', max_length=13, unique=True, validators=[books.validators.validate_isbn]),
        ),
        migrations.AlterField(
            model_name='book',
            name='supplier_country',
            field=models.CharField(help_text='Codigo de pais de dos letras, por ejemplo ES.', max_length=2, validators=[django.core.validators.RegexValidator(message='supplier_country debe ser un codigo de pais de dos letras.', regex='^[A-Za-z]{2}$')]),
        ),
    ]
